app <- ShinyDriver$new("../../")
app$snapshotInit("testChangeEDASliders")

app$snapshot()
app$setInputs(household_lifestage = c("CORE", "ADULTS"))
app$setInputs(household_lifestage = c("CORE", "ADULTS", "TEEN"))
app$setInputs(household_lifestage = c("CORE", "ADULTS", "TEEN", "YOUNG ADULTS", "TWEEN"))
app$setInputs(household_lifestage = c("CORE", "ADULTS", "TEEN", "YOUNG ADULTS", "TWEEN", "SENIORS", "PREK"))
app$snapshot()
app$setInputs(night_count = c(0, 17))
app$setInputs(night_count = c(6, 17))
app$setInputs(income = c(8750, 216923))
app$setInputs(income = c(69410, 216923))
app$setInputs(networth = c(76250, 625000))
app$setInputs(networth = c(76250, 431250))
